const fs = require("fs");
const path = require("path");

// Mapeamento completo de tipos para todos os nomes do seu JSON
const tiposPorPokemon = {
	Bulbasaur: ["/assets/grass.png", "/assets/poison.png"],
	Ivysaur: ["/assets/grass.png", "/assets/poison.png"],
	Venusaur: ["/assets/grass.png", "/assets/poison.png"],
	Charmander: ["/assets/fire.png"],
	Charmeleon: ["/assets/fire.png"],
	Charizard: ["/assets/fire.png", "/assets/flying.png"],
	Squirtle: ["/assets/water.png"],
	Wartortle: ["/assets/water.png"],
	Blastoise: ["/assets/water.png"],
	Caterpie: ["/assets/bug.png"],
	Metapod: ["/assets/bug.png"],
	Butterfree: ["/assets/bug.png", "/assets/flying.png"],
	Weedle: ["/assets/bug.png", "/assets/poison.png"],
	Kakuna: ["/assets/bug.png", "/assets/poison.png"],
	Beedrill: ["/assets/bug.png", "/assets/poison.png"],
	Pidgey: ["/assets/normal.png", "/assets/flying.png"],
	Pidgeotto: ["/assets/normal.png", "/assets/flying.png"],
	Pidgeot: ["/assets/normal.png", "/assets/flying.png"],
	Rattata: ["/assets/normal.png"],
	Raticate: ["/assets/normal.png"],
	Spearow: ["/assets/normal.png", "/assets/flying.png"],
	Fearow: ["/assets/normal.png", "/assets/flying.png"],
	Ekans: ["/assets/poison.png"],
	Arbok: ["/assets/poison.png"],
	Pikachu: ["/assets/electric.png"],
	"Alolan Raichu": ["/assets/electric.png", "/assets/psychic.png"],
	Raichu: ["/assets/electric.png"],
	Sandshrew: ["/assets/ground.png"],
	Sandslash: ["/assets/ground.png"],
	Nidoranfe: ["/assets/poison.png"],
	Nidorina: ["/assets/poison.png"],
	Nidoqueen: ["/assets/poison.png", "/assets/ground.png"],
	Nidoranma: ["/assets/poison.png"],
	Nidorino: ["/assets/poison.png"],
	Nidoking: ["/assets/poison.png", "/assets/ground.png"],
	Clefairy: ["/assets/fairy.png"],
	Clefable: ["/assets/fairy.png"],
	Vulpix: ["/assets/fire.png"],
	Ninetales: ["/assets/fire.png"],
	Jigglypuff: ["/assets/normal.png", "/assets/fairy.png"],
	Wigglytuff: ["/assets/normal.png", "/assets/fairy.png"],
	Zubat: ["/assets/poison.png", "/assets/flying.png"],
	Golbat: ["/assets/poison.png", "/assets/flying.png"],
	Oddish: ["/assets/grass.png", "/assets/poison.png"],
	Gloom: ["/assets/grass.png", "/assets/poison.png"],
	Vileplume: ["/assets/grass.png", "/assets/poison.png"],
	Paras: ["/assets/bug.png", "/assets/grass.png"],
	Parasect: ["/assets/bug.png", "/assets/grass.png"],
	Venonat: ["/assets/bug.png", "/assets/poison.png"],
	Venomoth: ["/assets/bug.png", "/assets/poison.png"],
	"Alolan Diglett": ["/assets/ground.png", "/assets/steel.png"],
	Diglett: ["/assets/ground.png"],
	"Alolan Dugtrio": ["/assets/ground.png", "/assets/steel.png"],
	Dugtrio: ["/assets/ground.png"],
	"Alolan Meowth": ["/assets/dark.png"],
	"Galarian Meowth": ["/assets/steel.png"],
	Meowth: ["/assets/normal.png"],
	"Alolan Persian": ["/assets/dark.png"],
	Persian: ["/assets/normal.png"],
	Psyduck: ["/assets/water.png"],
	Golduck: ["/assets/water.png"],
	Mankey: ["/assets/fighting.png"],
	Primeape: ["/assets/fighting.png"],
	Growlithe: ["/assets/fire.png"],
	Arcanine: ["/assets/fire.png"],
	Poliwag: ["/assets/water.png"],
	Poliwhirl: ["/assets/water.png"],
	Poliwrath: ["/assets/water.png", "/assets/fighting.png"],
	Abra: ["/assets/psychic.png"],
	Kadabra: ["/assets/psychic.png"],
	Alakazam: ["/assets/psychic.png"],
	Machop: ["/assets/fighting.png"],
	Machoke: ["/assets/fighting.png"],
	Machamp: ["/assets/fighting.png"],
	Bellsprout: ["/assets/grass.png", "/assets/poison.png"],
	Weepinbell: ["/assets/grass.png", "/assets/poison.png"],
	Victreebel: ["/assets/grass.png", "/assets/poison.png"],
	Tentacool: ["/assets/water.png", "/assets/poison.png"],
	Tentacruel: ["/assets/water.png", "/assets/poison.png"],
	"Alolan Geodude": ["/assets/rock.png", "/assets/electric.png"],
	Geodude: ["/assets/rock.png", "/assets/ground.png"],
	"Alolan Graveler": ["/assets/rock.png", "/assets/electric.png"],
	Graveler: ["/assets/rock.png", "/assets/ground.png"],
	Golem: ["/assets/rock.png", "/assets/ground.png"],
	"Galarian Ponyta": ["/assets/psychic.png"],
	Ponyta: ["/assets/fire.png"],
	"Galarian Rapidash": ["/assets/psychic.png", "/assets/fairy.png"],
	Rapidash: ["/assets/fire.png"],
	Slowpoke: ["/assets/water.png", "/assets/psychic.png"],
	Slowbro: ["/assets/water.png", "/assets/psychic.png"],
	Magnemite: ["/assets/electric.png", "/assets/steel.png"],
	Magneton: ["/assets/electric.png", "/assets/steel.png"],
	"Farfetch'd": ["/assets/normal.png", "/assets/flying.png"],
	"Galarian FarfetchD": ["/assets/fighting.png"],
	Doduo: ["/assets/normal.png", "/assets/flying.png"],
	Dodrio: ["/assets/normal.png", "/assets/flying.png"],
	Seel: ["/assets/water.png"],
	Dewgong: ["/assets/water.png", "/assets/ice.png"],
	"Alolan Grimer": ["/assets/poison.png", "/assets/dark.png"],
	Grimer: ["/assets/poison.png"],
	"Alolan Muk": ["/assets/poison.png", "/assets/dark.png"],
	Muk: ["/assets/poison.png"],
	Shellder: ["/assets/water.png"],
	Cloyster: ["/assets/water.png", "/assets/ice.png"],
	Gastly: ["/assets/ghost.png", "/assets/poison.png"],
	Haunter: ["/assets/ghost.png", "/assets/poison.png"],
	Gengar: ["/assets/ghost.png", "/assets/poison.png"],
	Onix: ["/assets/rock.png", "/assets/ground.png"],
	Drowzee: ["/assets/psychic.png"],
	Hypno: ["/assets/psychic.png"],
	Krabby: ["/assets/water.png"],
	Kingler: ["/assets/water.png"],
	Voltorb: ["/assets/electric.png"],
	Electrode: ["/assets/electric.png"],
	Exeggcute: ["/assets/grass.png", "/assets/psychic.png"],
	Exeggutor: ["/assets/grass.png", "/assets/psychic.png"],
	Cubone: ["/assets/ground.png"],
	Marowak: ["/assets/ground.png"],
	Hitmonlee: ["/assets/fighting.png"],
	Hitmonchan: ["/assets/fighting.png"],
	Lickitung: ["/assets/normal.png"],
	Koffing: ["/assets/poison.png"],
	Weezing: ["/assets/poison.png"],
	Rhyhorn: ["/assets/ground.png", "/assets/rock.png"],
	Rhydon: ["/assets/ground.png", "/assets/rock.png"],
	Chansey: ["/assets/normal.png"],
	Tangela: ["/assets/grass.png"],
	Kangaskhan: ["/assets/normal.png"],
	Horsea: ["/assets/water.png"],
	Seadra: ["/assets/water.png"],
	Goldeen: ["/assets/water.png"],
	Seaking: ["/assets/water.png"],
	Staryu: ["/assets/water.png"],
	Starmie: ["/assets/water.png", "/assets/psychic.png"],
	"Mr. Mime": ["/assets/psychic.png", "/assets/fairy.png"],
	Scyther: ["/assets/bug.png", "/assets/flying.png"],
	Jynx: ["/assets/ice.png", "/assets/psychic.png"],
	Electabuzz: ["/assets/electric.png"],
	Magmar: ["/assets/fire.png"],
	Pinsir: ["/assets/bug.png"],
	Tauros: ["/assets/normal.png"],
	"Big Magikarp": ["/assets/water.png"],
	"Giant Magikarp": ["/assets/water.png"],
	Magikarp: ["/assets/water.png"],
	"Mini Magikarp": ["/assets/water.png"],
	Gyarados: ["/assets/water.png", "/assets/flying.png"],
	Lapras: ["/assets/water.png", "/assets/ice.png"],
	Eevee: ["/assets/normal.png"],
	Vaporeon: ["/assets/water.png"],
	Jolteon: ["/assets/electric.png"],
	Flareon: ["/assets/fire.png"],
	Porygon: ["/assets/normal.png"],
	Omanyte: ["/assets/rock.png", "/assets/water.png"],
	Omastar: ["/assets/rock.png", "/assets/water.png"],
	Kabuto: ["/assets/rock.png", "/assets/water.png"],
	Kabutops: ["/assets/rock.png", "/assets/water.png"],
	Snorlax: ["/assets/normal.png"],
	Dratini: ["/assets/dragon.png"],
	Dragonair: ["/assets/dragon.png"],
	Dragonite: ["/assets/dragon.png", "/assets/flying.png"],
	Chikorita: ["/assets/grass.png"],
	Bayleef: ["/assets/grass.png"],
	Meganium: ["/assets/grass.png"],
	Cyndaquil: ["/assets/fire.png"],
	Quilava: ["/assets/fire.png"],
	Typhlosion: ["/assets/fire.png"],
	Totodile: ["/assets/water.png"],
	Croconaw: ["/assets/water.png"],
	Feraligatr: ["/assets/water.png"],
	Sentret: ["/assets/normal.png"],
	Furret: ["/assets/normal.png"],
	Hoothoot: ["/assets/normal.png", "/assets/flying.png"],
	Noctowl: ["/assets/normal.png", "/assets/flying.png"],
	Ledyba: ["/assets/bug.png", "/assets/flying.png"],
	Ledian: ["/assets/bug.png", "/assets/flying.png"],
	Spinarak: ["/assets/bug.png", "/assets/poison.png"],
	Ariados: ["/assets/bug.png", "/assets/poison.png"],
	Crobat: ["/assets/poison.png", "/assets/flying.png"],
	Chinchou: ["/assets/water.png", "/assets/electric.png"],
	Lanturn: ["/assets/water.png", "/assets/electric.png"],
	"Dark Pichu": ["/assets/electric.png"],
	Pichu: ["/assets/electric.png"],
	Cleffa: ["/assets/fairy.png"],
	Igglybuff: ["/assets/normal.png", "/assets/fairy.png"],
	Togepi: ["/assets/fairy.png"],
	Togetic: ["/assets/fairy.png", "/assets/flying.png"],
	Natu: ["/assets/psychic.png", "/assets/flying.png"],
	Xatu: ["/assets/psychic.png", "/assets/flying.png"],
	Mareep: ["/assets/electric.png"],
	Flaaffy: ["/assets/electric.png"],
	Ampharos: ["/assets/electric.png"],
	Bellossom: ["/assets/grass.png"],
	Marill: ["/assets/water.png", "/assets/fairy.png"],
	Azumarill: ["/assets/water.png", "/assets/fairy.png"],
	Sudowoodo: ["/assets/rock.png"],
	Politoed: ["/assets/water.png"],
	Hoppip: ["/assets/grass.png", "/assets/flying.png"],
	Skiploom: ["/assets/grass.png", "/assets/flying.png"],
	Jumpluff: ["/assets/grass.png", "/assets/flying.png"],
	Aipom: ["/assets/normal.png"],
	Sunkern: ["/assets/grass.png"],
	Sunflora: ["/assets/grass.png"],
	Yanma: ["/assets/bug.png", "/assets/flying.png"],
	Wooper: ["/assets/water.png", "/assets/ground.png"],
	Quagsire: ["/assets/water.png", "/assets/ground.png"],
	Espeon: ["/assets/psychic.png"],
	Umbreon: ["/assets/dark.png"],
	Murkrow: ["/assets/dark.png", "/assets/flying.png"],
	Slowking: ["/assets/water.png", "/assets/psychic.png"],
	Misdreavus: ["/assets/ghost.png"],
	Wobbuffet: ["/assets/psychic.png"],
	Girafarig: ["/assets/normal.png", "/assets/psychic.png"],
	Pineco: ["/assets/bug.png"],
	Forretress: ["/assets/bug.png", "/assets/steel.png"],
	Dunsparce: ["/assets/normal.png"],
	Gligar: ["/assets/ground.png", "/assets/flying.png"],
	Steelix: ["/assets/steel.png", "/assets/ground.png"],
	Snubbull: ["/assets/fairy.png"],
	Granbull: ["/assets/fairy.png"],
	Qwilfish: ["/assets/water.png", "/assets/poison.png"],
	Shuckle: ["/assets/bug.png", "/assets/rock.png"],
	Heracross: ["/assets/bug.png", "/assets/fighting.png"],
	Sneasel: ["/assets/dark.png", "/assets/ice.png"],
	Teddiursa: ["/assets/normal.png"],
	Ursaring: ["/assets/normal.png"],
	Slugma: ["/assets/fire.png"],
	Magcargo: ["/assets/fire.png", "/assets/rock.png"],
	Swinub: ["/assets/ice.png", "/assets/ground.png"],
	Piloswine: ["/assets/ice.png", "/assets/ground.png"],
	Corsola: ["/assets/water.png", "/assets/rock.png"],
	Remoraid: ["/assets/water.png"],
	Octillery: ["/assets/water.png"],
	Delibird: ["/assets/ice.png", "/assets/flying.png"],
	Mantine: ["/assets/water.png", "/assets/flying.png"],
	Skarmory: ["/assets/steel.png", "/assets/flying.png"],
	Houndour: ["/assets/dark.png", "/assets/fire.png"],
	Houndoom: ["/assets/dark.png", "/assets/fire.png"],
	Kingdra: ["/assets/water.png", "/assets/dragon.png"],
	Phanpy: ["/assets/ground.png"],
	Donphan: ["/assets/ground.png"],
	Porygon2: ["/assets/normal.png"],
	Stantler: ["/assets/normal.png"],
	"Smeargle 2": ["/assets/normal.png"],
	"Smeargle 3": ["/assets/normal.png"],
	"Smeargle 4": ["/assets/normal.png"],
	"Smeargle 5": ["/assets/normal.png"],
	Tyrogue: ["/assets/fighting.png"],
	Hitmontop: ["/assets/fighting.png"],
	Smoochum: ["/assets/ice.png", "/assets/psychic.png"],
	Elekid: ["/assets/electric.png"],
	Magby: ["/assets/fire.png"],
	Miltank: ["/assets/normal.png"],
	Blissey: ["/assets/normal.png"],
	Larvitar: ["/assets/rock.png", "/assets/ground.png"],
	Pupitar: ["/assets/rock.png", "/assets/ground.png"],
	Tyranitar: ["/assets/rock.png", "/assets/dark.png"],
	Treecko: ["/assets/grass.png"],
	Grovyle: ["/assets/grass.png"],
	Sceptile: ["/assets/grass.png"],
	Torchic: ["/assets/fire.png"],
	Combusken: ["/assets/fire.png", "/assets/fighting.png"],
	Blaziken: ["/assets/fire.png", "/assets/fighting.png"],
	Mudkip: ["/assets/water.png"],
	Marshtomp: ["/assets/water.png", "/assets/ground.png"],
	Swampert: ["/assets/water.png", "/assets/ground.png"],
	Poochyena: ["/assets/dark.png"],
	Mightyena: ["/assets/dark.png"],
	Zigzagoon: ["/assets/normal.png"],
	Linoone: ["/assets/normal.png"],
	Wurmple: ["/assets/bug.png"],
	Silcoon: ["/assets/bug.png"],
	Beautifly: ["/assets/bug.png", "/assets/flying.png"],
	Cascoon: ["/assets/bug.png"],
	Dustox: ["/assets/bug.png", "/assets/poison.png"],
	Lotad: ["/assets/water.png", "/assets/grass.png"],
	Lombre: ["/assets/water.png", "/assets/grass.png"],
	Ludicolo: ["/assets/water.png", "/assets/grass.png"],
	Seedot: ["/assets/grass.png"],
	Nuzleaf: ["/assets/grass.png", "/assets/dark.png"],
	Shiftry: ["/assets/grass.png", "/assets/dark.png"],
	Taillow: ["/assets/normal.png", "/assets/flying.png"],
	Swellow: ["/assets/normal.png", "/assets/flying.png"],
	Wingull: ["/assets/water.png", "/assets/flying.png"],
	Pelipper: ["/assets/water.png", "/assets/flying.png"],
	Ralts: ["/assets/psychic.png", "/assets/fairy.png"],
	Kirlia: ["/assets/psychic.png", "/assets/fairy.png"],
	Gardevoir: ["/assets/psychic.png", "/assets/fairy.png"],
	Surskit: ["/assets/bug.png", "/assets/water.png"],
	Masquerain: ["/assets/bug.png", "/assets/flying.png"],
	Shroomish: ["/assets/grass.png"],
	Breloom: ["/assets/grass.png", "/assets/fighting.png"],
	Slakoth: ["/assets/normal.png"],
	Vigoroth: ["/assets/normal.png"],
	Slaking: ["/assets/normal.png"],
	Nincada: ["/assets/bug.png", "/assets/ground.png"],
	Ninjask: ["/assets/bug.png", "/assets/flying.png"],
	Shedinja: ["/assets/bug.png", "/assets/ghost.png"],
	Whismur: ["/assets/normal.png"],
	Loudred: ["/assets/normal.png"],
	Exploud: ["/assets/normal.png"],
	Makuhita: ["/assets/fighting.png"],
	Hariyama: ["/assets/fighting.png"],
	Nosepass: ["/assets/rock.png"],
	Sableye: ["/assets/dark.png", "/assets/ghost.png"],
	Mawile: ["/assets/steel.png", "/assets/fairy.png"],
	Aron: ["/assets/steel.png", "/assets/rock.png"],
	Lairon: ["/assets/steel.png", "/assets/rock.png"],
	Aggron: ["/assets/steel.png", "/assets/rock.png"],
	Meditite: ["/assets/fighting.png", "/assets/psychic.png"],
	Medicham: ["/assets/fighting.png", "/assets/psychic.png"],
	Electrike: ["/assets/electric.png"],
	Manectric: ["/assets/electric.png"],
	"Minun and Plusle": ["/assets/electric.png"],
	Plusle: ["/assets/electric.png"],
	Minun: ["/assets/electric.png"],
	Roselia: ["/assets/grass.png", "/assets/poison.png"],
	Gulpin: ["/assets/poison.png"],
	Swalot: ["/assets/poison.png"],
	Carvanha: ["/assets/water.png", "/assets/dark.png"],
	Sharpedo: ["/assets/water.png", "/assets/dark.png"],
	Numel: ["/assets/fire.png", "/assets/ground.png"],
	Camerupt: ["/assets/fire.png", "/assets/ground.png"],
	Torkoal: ["/assets/fire.png"],
	Spoink: ["/assets/psychic.png"],
	Grumpig: ["/assets/psychic.png"],
	Trapinch: ["/assets/ground.png"],
	Vibrava: ["/assets/ground.png", "/assets/dragon.png"],
	Flygon: ["/assets/ground.png", "/assets/dragon.png"],
	Cacnea: ["/assets/grass.png"],
	Cacturne: ["/assets/grass.png", "/assets/dark.png"],
	Swablu: ["/assets/normal.png", "/assets/flying.png"],
	Altaria: ["/assets/dragon.png", "/assets/flying.png"],
	Zangoose: ["/assets/normal.png"],
	Seviper: ["/assets/poison.png"],
	Lunatone: ["/assets/rock.png", "/assets/psychic.png"],
	Solrock: ["/assets/rock.png", "/assets/psychic.png"],
	Barboach: ["/assets/water.png", "/assets/ground.png"],
	Whiscash: ["/assets/water.png", "/assets/ground.png"],
	Corphish: ["/assets/water.png"],
	Crawdaunt: ["/assets/water.png", "/assets/dark.png"],
	Baltoy: ["/assets/ground.png", "/assets/psychic.png"],
	Claydol: ["/assets/ground.png", "/assets/psychic.png"],
	Lileep: ["/assets/rock.png", "/assets/grass.png"],
	Cradily: ["/assets/rock.png", "/assets/grass.png"],
	Anorith: ["/assets/rock.png", "/assets/bug.png"],
	Armaldo: ["/assets/rock.png", "/assets/bug.png"],
	Feebas: ["/assets/water.png"],
	Milotic: ["/assets/water.png"],
	Castform: ["/assets/normal.png"],
	Kecleon: ["/assets/normal.png"],
	Shuppet: ["/assets/ghost.png"],
	Banette: ["/assets/ghost.png"],
	Duskull: ["/assets/ghost.png"],
	Dusclops: ["/assets/ghost.png"],
	Tropius: ["/assets/grass.png", "/assets/flying.png"],
	Absol: ["/assets/dark.png"],
	Wynaut: ["/assets/psychic.png"],
	Snorunt: ["/assets/ice.png"],
	Glalie: ["/assets/ice.png"],
	Spheal: ["/assets/ice.png", "/assets/water.png"],
	Sealeo: ["/assets/ice.png", "/assets/water.png"],
	Walrein: ["/assets/ice.png", "/assets/water.png"],
	Bagon: ["/assets/dragon.png"],
	Shelgon: ["/assets/dragon.png"],
	Salamence: ["/assets/dragon.png", "/assets/flying.png"],
	Beldum: ["/assets/steel.png", "/assets/psychic.png"],
	Metang: ["/assets/steel.png", "/assets/psychic.png"],
	Metagross: ["/assets/steel.png", "/assets/psychic.png"],
	Turtwig: ["/assets/grass.png"],
	Grotle: ["/assets/grass.png"],
	Torterra: ["/assets/grass.png", "/assets/ground.png"],
	Chimchar: ["/assets/fire.png"],
	Monferno: ["/assets/fire.png", "/assets/fighting.png"],
	Infernape: ["/assets/fire.png", "/assets/fighting.png"],
	Piplup: ["/assets/water.png"],
	Prinplup: ["/assets/water.png"],
	Empoleon: ["/assets/water.png", "/assets/steel.png"],
	Starly: ["/assets/normal.png", "/assets/flying.png"],
	Staravia: ["/assets/normal.png", "/assets/flying.png"],
	Staraptor: ["/assets/normal.png", "/assets/flying.png"],
	Kricketot: ["/assets/bug.png"],
	Kricketune: ["/assets/bug.png"],
	Shinx: ["/assets/electric.png"],
	Luxio: ["/assets/electric.png"],
	Luxray: ["/assets/electric.png"],
	Roserade: ["/assets/grass.png", "/assets/poison.png"],
	Cranidos: ["/assets/rock.png"],
	Rampardos: ["/assets/rock.png"],
	Shieldon: ["/assets/rock.png", "/assets/steel.png"],
	Bastiodon: ["/assets/rock.png", "/assets/steel.png"],
	Burmy: ["/assets/bug.png"],
	Wormadam: ["/assets/bug.png", "/assets/grass.png"], // Forma Plant Cloak
	Combee: ["/assets/bug.png", "/assets/flying.png"],
	Vespiquen: ["/assets/bug.png", "/assets/flying.png"],
	Pachirisu: ["/assets/electric.png"],
	Buizel: ["/assets/water.png"],
	Floatzel: ["/assets/water.png"],
	Ambipom: ["/assets/normal.png"],
	Drifloon: ["/assets/ghost.png", "/assets/flying.png"],
	Drifblim: ["/assets/ghost.png", "/assets/flying.png"],
	Buneary: ["/assets/normal.png"],
	Lopunny: ["/assets/normal.png"],
	Mismagius: ["/assets/ghost.png"],
	Honchkrow: ["/assets/dark.png", "/assets/flying.png"],
	Bronzor: ["/assets/steel.png", "/assets/psychic.png"],
	Bronzong: ["/assets/steel.png", "/assets/psychic.png"],
	Spiritomb: ["/assets/ghost.png", "/assets/dark.png"],
	Gible: ["/assets/dragon.png", "/assets/ground.png"],
	Gabite: ["/assets/dragon.png", "/assets/ground.png"],
	Garchomp: ["/assets/dragon.png", "/assets/ground.png"],
	Munchlax: ["/assets/normal.png"],
	Riolu: ["/assets/fighting.png"],
	Lucario: ["/assets/fighting.png", "/assets/steel.png"],
	Hippopotas: ["/assets/ground.png"],
	Hippowdon: ["/assets/ground.png"],
	Skorupi: ["/assets/poison.png", "/assets/bug.png"],
	Drapion: ["/assets/poison.png", "/assets/dark.png"],
	Croagunk: ["/assets/poison.png", "/assets/fighting.png"],
	Toxicroak: ["/assets/poison.png", "/assets/fighting.png"],
	Mantyke: ["/assets/water.png", "/assets/flying.png"],
	Snover: ["/assets/grass.png", "/assets/ice.png"],
	Abomasnow: ["/assets/grass.png", "/assets/ice.png"],
	Weavile: ["/assets/dark.png", "/assets/ice.png"],
	Magnezone: ["/assets/electric.png", "/assets/steel.png"],
	Lickilicky: ["/assets/normal.png"],
	Rhyperior: ["/assets/ground.png", "/assets/rock.png"],
	Electivire: ["/assets/electric.png"],
	Magmortar: ["/assets/fire.png"],
	Togekiss: ["/assets/fairy.png", "/assets/flying.png"],
	Yanmega: ["/assets/bug.png", "/assets/flying.png"],
	Leafeon: ["/assets/grass.png"],
	Glaceon: ["/assets/ice.png"],
	Gliscor: ["/assets/ground.png", "/assets/flying.png"],
	Gallade: ["/assets/psychic.png", "/assets/fighting.png"],
	Probopass: ["/assets/rock.png", "/assets/steel.png"],
	Dusknoir: ["/assets/ghost.png"],
	Froslass: ["/assets/ice.png", "/assets/ghost.png"],
	Rotom: ["/assets/electric.png", "/assets/ghost.png"],
	Pansear: ["/assets/fire.png"],
	Simisear: ["/assets/fire.png"],
	Blitzle: ["/assets/electric.png"],
	Zebstrika: ["/assets/electric.png"],
	Drilbur: ["/assets/ground.png"],
	Excadrill: ["/assets/ground.png", "/assets/steel.png"],
	Audino: ["/assets/normal.png"],
	Timburr: ["/assets/fighting.png"],
	Gurdurr: ["/assets/fighting.png"],
	Throh: ["/assets/fighting.png"],
	Sawk: ["/assets/fighting.png"],
	Cottonee: ["/assets/grass.png", "/assets/fairy.png"],
	Whimsicott: ["/assets/grass.png", "/assets/fairy.png"],
	Petilil: ["/assets/grass.png"],
	Lilligant: ["/assets/grass.png"],
	Sandile: ["/assets/ground.png", "/assets/dark.png"],
	Krokorok: ["/assets/ground.png", "/assets/dark.png"],
	Krookodile: ["/assets/ground.png", "/assets/dark.png"],
	Darumaka: ["/assets/fire.png"],
	"Galarian Darumaka": ["/assets/ice.png"],
	Darmanitan: ["/assets/fire.png"],
	"Galarian Darmanitan": ["/assets/ice.png"],
	Dwebble: ["/assets/bug.png", "/assets/rock.png"],
	Crustle: ["/assets/bug.png", "/assets/rock.png"],
	Scraggy: ["/assets/dark.png", "/assets/fighting.png"],
	Scrafty: ["/assets/dark.png", "/assets/fighting.png"],
	Yamask: ["/assets/ghost.png"],
	Cofagrigus: ["/assets/ghost.png"],
	Tirtouga: ["/assets/water.png", "/assets/rock.png"],
	Carracosta: ["/assets/water.png", "/assets/rock.png"],
	Archen: ["/assets/rock.png", "/assets/flying.png"],
	Archeops: ["/assets/rock.png", "/assets/flying.png"],
	Trubbish: ["/assets/poison.png"],
	Garbodor: ["/assets/poison.png"],
	Gothita: ["/assets/psychic.png"],
	Gothorita: ["/assets/psychic.png"],
	Gothitelle: ["/assets/psychic.png"],
	Vanillite: ["/assets/ice.png"],
	Vanillish: ["/assets/ice.png"],
	Vanilluxe: ["/assets/ice.png"],
	Emolga: ["/assets/electric.png", "/assets/flying.png"],
	Alomomola: ["/assets/water.png"],
	Joltik: ["/assets/bug.png", "/assets/electric.png"],
	Galvantula: ["/assets/bug.png", "/assets/electric.png"],
	Ferroseed: ["/assets/grass.png", "/assets/steel.png"],
	Ferrothorn: ["/assets/grass.png", "/assets/steel.png"],
	Klink: ["/assets/steel.png"],
	Klinklang: ["/assets/steel.png"],
	Tynamo: ["/assets/electric.png"],
	Eelektrik: ["/assets/electric.png"],
	Eelektross: ["/assets/electric.png"],
	Litwick: ["/assets/ghost.png", "/assets/fire.png"],
	Lampent: ["/assets/ghost.png", "/assets/fire.png"],
	Chandelure: ["/assets/ghost.png", "/assets/fire.png"],
	Axew: ["/assets/dragon.png"],
	Fraxure: ["/assets/dragon.png"],
	Haxorus: ["/assets/dragon.png"],
	Cubchoo: ["/assets/ice.png"],
	Beartic: ["/assets/ice.png"],
	Shelmet: ["/assets/bug.png"],
	Accelgor: ["/assets/bug.png"],
	Mienfoo: ["/assets/fighting.png"],
	Mienshao: ["/assets/fighting.png"],
	Druddigon: ["/assets/dragon.png"],
	Golett: ["/assets/ground.png", "/assets/ghost.png"],
	Golurk: ["/assets/ground.png", "/assets/ghost.png"],
	Pawniard: ["/assets/dark.png", "/assets/steel.png"],
	Bisharp: ["/assets/dark.png", "/assets/steel.png"],
	Rufflet: ["/assets/normal.png", "/assets/flying.png"],
	Braviary: ["/assets/normal.png", "/assets/flying.png"],
	Heatmor: ["/assets/fire.png"],
	Deino: ["/assets/dark.png", "/assets/dragon.png"],
	Zweilous: ["/assets/dark.png", "/assets/dragon.png"],
	Hydreigon: ["/assets/dark.png", "/assets/dragon.png"],
	Larvesta: ["/assets/bug.png", "/assets/fire.png"],
	Volcarona: ["/assets/bug.png", "/assets/fire.png"],
	Bunnelby: ["/assets/normal.png"],
	Diggersby: ["/assets/normal.png", "/assets/ground.png"],
	Fletchling: ["/assets/normal.png", "/assets/flying.png"],
	Fletchinder: ["/assets/fire.png", "/assets/flying.png"],
	Talonflame: ["/assets/fire.png", "/assets/flying.png"],
	Litleo: ["/assets/fire.png", "/assets/normal.png"],
	"Pyroar Female": ["/assets/fire.png", "/assets/normal.png"],
	Pyroar: ["/assets/fire.png", "/assets/normal.png"],
	Flabébé: ["/assets/fairy.png"],
	Floette: ["/assets/fairy.png"],
	Florges: ["/assets/fairy.png"],
	Skiddo: ["/assets/grass.png"],
	Gogoat: ["/assets/grass.png"],
	Pancham: ["/assets/fighting.png"],
	Pangoro: ["/assets/fighting.png", "/assets/dark.png"],
	Espurr: ["/assets/psychic.png"],
	Meowstic: ["/assets/psychic.png"],
	Honedge: ["/assets/steel.png", "/assets/ghost.png"],
	Doublade: ["/assets/steel.png", "/assets/ghost.png"],
	Aegislash: ["/assets/steel.png", "/assets/ghost.png"],
	Spritzee: ["/assets/fairy.png"],
	Aromatisse: ["/assets/fairy.png"],
	Skrelp: ["/assets/poison.png", "/assets/water.png"],
	Dragalge: ["/assets/poison.png", "/assets/dragon.png"],
	Sylveon: ["/assets/fairy.png"],
	Dedenne: ["/assets/electric.png", "/assets/fairy.png"],
	Carbink: ["/assets/rock.png", "/assets/fairy.png"],
	Goomy: ["/assets/dragon.png"],
	Sliggoo: ["/assets/dragon.png"],
	Goodra: ["/assets/dragon.png"],
	Klefki: ["/assets/steel.png", "/assets/fairy.png"],
	Grubbin: ["/assets/bug.png"],
	Charjabug: ["/assets/bug.png", "/assets/electric.png"],
	Vikavolt: ["/assets/bug.png", "/assets/electric.png"],
	Rockruff: ["/assets/rock.png"],
	"Lycanroc Dusk Form": ["/assets/rock.png"],
	"Lycanroc Midnight Form": ["/assets/rock.png"],
	Lycanroc: ["/assets/rock.png"],
	Mudbray: ["/assets/ground.png"],
	Mudsdale: ["/assets/ground.png"],
	Sandygast: ["/assets/ghost.png", "/assets/ground.png"],
	Palossand: ["/assets/ghost.png", "/assets/ground.png"],
	Turtonator: ["/assets/fire.png", "/assets/dragon.png"],
	Togedemaru: ["/assets/electric.png", "/assets/steel.png"],
	Mimikyu: ["/assets/ghost.png", "/assets/fairy.png"],
	Scorbunny: ["/assets/fire.png"],
	Raboot: ["/assets/fire.png"],
	Cinderace: ["/assets/fire.png"],
	Applin: ["/assets/grass.png", "/assets/dragon.png"],
	Flappe: ["/assets/grass.png", "/assets/dragon.png"],
	Appletun: ["/assets/grass.png", "/assets/dragon.png"],
	Silicobra: ["/assets/ground.png"],
	Sandaconda: ["/assets/ground.png"],
	Toxel: ["/assets/electric.png", "/assets/poison.png"],
	"Toxtricity Low Key Form": ["/assets/electric.png", "/assets/poison.png"],
	Toxtricity: ["/assets/electric.png", "/assets/poison.png"],
	Hatenna: ["/assets/psychic.png"],
	Hattrem: ["/assets/psychic.png"],
	Hatterene: ["/assets/psychic.png", "/assets/fairy.png"],
	Perrserker: ["/assets/steel.png"],
	Cursola: ["/assets/ghost.png"],
	"Sirfetch'D": ["/assets/fighting.png"],
	Milcery: ["/assets/fairy.png"],
	Alcremie: ["/assets/fairy.png"],
	Cufant: ["/assets/steel.png"],
	Copperajah: ["/assets/steel.png"],
	Tangrowth: ["/assets/grass.png"],
	Klang: ["/assets/steel.png"],
	Scizor: ["/assets/bug.png", "/assets/steel.png"],
};

// Caminho do arquivo JSON
const jsonPath = path.join(__dirname, "..", "public", "pokemons.json");

// Lê o arquivo
const pokemons = JSON.parse(fs.readFileSync(jsonPath, "utf8"));

// Atualiza os tipos
const atualizados = pokemons.map((poke) => {
	if (!poke.tipos || !Array.isArray(poke.tipos) || poke.tipos.length === 0) {
		const tipos = tiposPorPokemon[poke.nome] || [];
		return { ...poke, tipos };
	}
	return poke;
});

// Salva o arquivo atualizado
fs.writeFileSync(jsonPath, JSON.stringify(atualizados, null, 4), "utf8");
console.log("Pokémons atualizados com tipos automaticamente!");
